/*
 * oultrasonic.h
 *
 *  Created on: Oct 16, 2022
 *      Author: Dell
 */

#ifndef OULTRASONIC_H_
#define OULTRASONIC_H_

#include "std_define_types.h"

/*******************************************************************************
 *                      Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_TRIGGER_PORT		PORTB_ID
#define ULTRASONIC_TRIGGER_PIN		PIN5
/*
#define ULTRASONIC_ECHO_PORT		PORTD_ID
#define ULTRASONIC_ECHO_PIN			PIN6
*/
#define SPEED_OF_SOUND				0.034

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description: function responsible for initialization of ultrasonic
 * 1-initialize ICU
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init();
/*
 * Description : function responsible for Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger();
/*
 * Function description: function responsible for reading distance using ultrasonic
 *  1- send the trigger pulse by using Ultrasonic_Trigger function.so ultrasonic start to produce echo pulse
 *	2- Start the measurements by the ICU from this moment.
 *
 *	Return: The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance();
/*
 * Function description:
 * This is the call back function called by the ICU driver,
 * we initialize the call back in Ultrasonic_init()
 * the function used to calculate the high time (pulse time) generated by the ultrasonic sensor
 * */
void Ultrasonic_edgeProcessing();

#endif /* OULTRASONIC_H_ */
